# Generated by Django 4.1.7 on 2023-06-30 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0036_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="img",
            field=models.ImageField(null=True, upload_to="pics"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stroll1.customer",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="img",
            field=models.ImageField(null=True, upload_to="pics"),
        ),
    ]
