# Generated by Django 4.0.6 on 2023-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll1', '0037_remove_feedback_user_customer_img_feedback_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
